# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import thread_management
import threading
import time
from os_design.directory_management import Directory
from os_design.disk_management import Disk
from os_design.memory_management import Memory
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

memory_index = 0

my_disk = Disk(4 * 1024 * 1024, 4 * 1024, 1024, 900, 124, 100)
my_disk.generate_group_link()
my_disk.generate_disk_block()

my_dir = Directory()

my_memory = Memory(256 * 1024, 64)
my_memory.create_memory_list()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 803)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(600, 390, 591, 391))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("gui_pic/ddb1ed50352ac65c6aedaf2bfbf2b21192138ab1.jpg"))
        self.image_label.setObjectName("image_label")
        self.messege_label = QtWidgets.QLabel(self.centralwidget)
        self.messege_label.setGeometry(QtCore.QRect(170, 150, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.messege_label.setFont(font)
        self.messege_label.setStyleSheet("font: 20pt \"Agency FB\";\n"
                                         "color: rgb(0, 85, 255);\n"
                                         "border-color: rgb(0, 170, 255);")
        self.messege_label.setObjectName("messege_label")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(300, 30, 511, 71))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet(
            "background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
            "color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.title_label.setTextFormat(QtCore.Qt.RichText)
        self.title_label.setScaledContents(False)
        self.title_label.setObjectName("title_label")
        self.image2_label = QtWidgets.QLabel(self.centralwidget)
        self.image2_label.setGeometry(QtCore.QRect(-110, 390, 691, 411))
        self.image2_label.setText("")
        self.image2_label.setPixmap(QtGui.QPixmap(
            "gui_pic/src=http___img1.youzy.cn_content_media_thumbs_p00074610.jpeg&refer=http___img1.youzy.jpg"))
        self.image2_label.setObjectName("image2_label")
        self.image3_label = QtWidgets.QLabel(self.centralwidget)
        self.image3_label.setGeometry(QtCore.QRect(1040, -10, 181, 221))
        self.image3_label.setText("")
        self.image3_label.setPixmap(QtGui.QPixmap("gui_pic/dq.jpg"))
        self.image3_label.setObjectName("image3_label")
        self.memory_button = QtWidgets.QPushButton(self.centralwidget)
        self.memory_button.setGeometry(QtCore.QRect(610, 270, 161, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.memory_button.setFont(font)
        self.memory_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.memory_button.setStyleSheet("font: 16pt \"华文新魏\";\n"
                                         "background-color: rgb(85, 255, 127);\n"
                                         "border-color: rgb(255, 255, 127);")
        self.memory_button.setObjectName("memory_button")
        self.dir_button = QtWidgets.QPushButton(self.centralwidget)
        self.dir_button.setGeometry(QtCore.QRect(870, 270, 171, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dir_button.setFont(font)
        self.dir_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dir_button.setStyleSheet("font: 16pt \"华文新魏\";\n"
                                      "background-color: rgb(85, 255, 127);\n"
                                      "border-color: rgb(255, 255, 127);")
        self.dir_button.setObjectName("dir_button")
        self.control_button = QtWidgets.QPushButton(self.centralwidget)
        self.control_button.setGeometry(QtCore.QRect(150, 270, 131, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.control_button.setFont(font)
        self.control_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.control_button.setStyleSheet("font: 16pt \"华文新魏\";\n"
                                          "background-color: rgb(85, 255, 127);\n"
                                          "border-color: rgb(255, 255, 127);")
        self.control_button.setObjectName("control_button")
        self.disk_button = QtWidgets.QPushButton(self.centralwidget)
        self.disk_button.setGeometry(QtCore.QRect(370, 270, 161, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.disk_button.setFont(font)
        self.disk_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.disk_button.setStyleSheet("font: 16pt \"华文新魏\";\n"
                                       "background-color: rgb(85, 255, 127);\n"
                                       "border-color: rgb(255, 255, 127);")
        self.disk_button.setObjectName("disk_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1188, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.messege_label.setText(_translate("MainWindow", "欢迎使用，请选择要进入的界面"))
        self.title_label.setText(_translate("MainWindow", "操作系统课程设计"))
        self.memory_button.setText(_translate("MainWindow", "内存块界面"))
        self.dir_button.setText(_translate("MainWindow", "目录信息界面"))
        self.control_button.setText(_translate("MainWindow", "控制界面"))
        self.disk_button.setText(_translate("MainWindow", "外存块界面"))


# 外存块界面
class Disk_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1296, 845)
        self.N_label_1 = QtWidgets.QLabel(Dialog)
        self.N_label_1.setGeometry(QtCore.QRect(150, 200, 91, 91))
        self.N_label_1.setStyleSheet("font: 75 20pt \"Cambria\";\n"
                                     "color: rgb(85, 85, 255);")
        self.N_label_1.setObjectName("N_label_1")
        self.S_free_label_1 = QtWidgets.QLabel(Dialog)
        self.S_free_label_1.setGeometry(QtCore.QRect(70, 270, 151, 52))
        self.S_free_label_1.setStyleSheet("font: 75 20pt \"Cambria\";\n"
                                          "color: rgb(85, 85, 255);")
        self.S_free_label_1.setObjectName("S_free_label_1")
        self.S_free_label_2 = QtWidgets.QLabel(Dialog)
        self.S_free_label_2.setGeometry(QtCore.QRect(70, 330, 151, 52))
        self.S_free_label_2.setStyleSheet("font: 75 20pt \"Cambria\";\n"
                                          "color: rgb(85, 85, 255);")
        self.S_free_label_2.setObjectName("S_free_label_2")
        self.S_free_label_3 = QtWidgets.QLabel(Dialog)
        self.S_free_label_3.setGeometry(QtCore.QRect(70, 770, 151, 52))
        self.S_free_label_3.setStyleSheet("font: 75 20pt \"Cambria\";\n"
                                          "color: rgb(85, 85, 255);")
        self.S_free_label_3.setObjectName("S_free_label_3")
        self.block_title_label = QtWidgets.QLabel(Dialog)
        self.block_title_label.setGeometry(QtCore.QRect(180, 130, 231, 71))
        self.block_title_label.setStyleSheet("font: 20pt \"华文新魏\";\n"
                                             "color: rgb(0, 85, 127);")
        self.block_title_label.setObjectName("block_title_label")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setGeometry(QtCore.QRect(40, 0, 461, 151))
        self.title_label.setStyleSheet("font: 36pt \"华文琥珀\";\n"
                                       "color: rgb(0, 85, 255);")
        self.title_label.setObjectName("title_label")
        self.arrow_label = QtWidgets.QLabel(Dialog)
        self.arrow_label.setGeometry(QtCore.QRect(380, 290, 201, 31))
        self.arrow_label.setText("")
        self.arrow_label.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_label.setObjectName("arrow_label")
        self.block_2_5_button = QtWidgets.QPushButton(Dialog)
        self.block_2_5_button.setGeometry(QtCore.QRect(550, 325, 151, 49))
        self.block_2_5_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_5_button.setObjectName("block_2_5_button")
        self.block_2_6_button = QtWidgets.QPushButton(Dialog)
        self.block_2_6_button.setGeometry(QtCore.QRect(550, 380, 151, 49))
        self.block_2_6_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_6_button.setObjectName("block_2_6_button")
        self.block_2_9_button = QtWidgets.QPushButton(Dialog)
        self.block_2_9_button.setGeometry(QtCore.QRect(550, 545, 151, 50))
        self.block_2_9_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_9_button.setObjectName("block_2_9_button")
        self.block_2_11_button = QtWidgets.QPushButton(Dialog)
        self.block_2_11_button.setGeometry(QtCore.QRect(550, 656, 151, 49))
        self.block_2_11_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                             "background-color: rgb(85, 170, 127);")
        self.block_2_11_button.setObjectName("block_2_11_button")
        self.block_2_7_button = QtWidgets.QPushButton(Dialog)
        self.block_2_7_button.setGeometry(QtCore.QRect(550, 435, 151, 49))
        self.block_2_7_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_7_button.setObjectName("block_2_7_button")
        self.block_2_1_button = QtWidgets.QPushButton(Dialog)
        self.block_2_1_button.setGeometry(QtCore.QRect(550, 104, 151, 49))
        self.block_2_1_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_1_button.setObjectName("block_2_1_button")
        self.block_2_10_button = QtWidgets.QPushButton(Dialog)
        self.block_2_10_button.setGeometry(QtCore.QRect(550, 601, 151, 49))
        self.block_2_10_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                             "background-color: rgb(85, 170, 127);")
        self.block_2_10_button.setObjectName("block_2_10_button")
        self.block_2_3_button = QtWidgets.QPushButton(Dialog)
        self.block_2_3_button.setGeometry(QtCore.QRect(550, 214, 151, 50))
        self.block_2_3_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_3_button.setObjectName("block_2_3_button")
        self.block_2_2_button = QtWidgets.QPushButton(Dialog)
        self.block_2_2_button.setGeometry(QtCore.QRect(550, 159, 151, 49))
        self.block_2_2_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_2_button.setObjectName("block_2_2_button")
        self.block_2_8_button = QtWidgets.QPushButton(Dialog)
        self.block_2_8_button.setGeometry(QtCore.QRect(550, 490, 151, 49))
        self.block_2_8_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_8_button.setObjectName("block_2_8_button")
        self.block_2_4_button = QtWidgets.QPushButton(Dialog)
        self.block_2_4_button.setGeometry(QtCore.QRect(550, 270, 151, 49))
        self.block_2_4_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_2_4_button.setObjectName("block_2_4_button")
        self.block_3_5_button = QtWidgets.QPushButton(Dialog)
        self.block_3_5_button.setGeometry(QtCore.QRect(1080, 325, 151, 49))
        self.block_3_5_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_5_button.setObjectName("block_3_5_button")
        self.block_3_6_button = QtWidgets.QPushButton(Dialog)
        self.block_3_6_button.setGeometry(QtCore.QRect(1080, 380, 151, 49))
        self.block_3_6_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_6_button.setObjectName("block_3_6_button")
        self.block_3_9_button = QtWidgets.QPushButton(Dialog)
        self.block_3_9_button.setGeometry(QtCore.QRect(1080, 545, 151, 50))
        self.block_3_9_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_9_button.setObjectName("block_3_9_button")
        self.block_3_11_button = QtWidgets.QPushButton(Dialog)
        self.block_3_11_button.setGeometry(QtCore.QRect(1080, 656, 151, 49))
        self.block_3_11_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                             "background-color: rgb(85, 170, 127);")
        self.block_3_11_button.setObjectName("block_3_11_button")
        self.block_3_7_button = QtWidgets.QPushButton(Dialog)
        self.block_3_7_button.setGeometry(QtCore.QRect(1080, 435, 151, 49))
        self.block_3_7_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_7_button.setObjectName("block_3_7_button")
        self.block_3_1_button = QtWidgets.QPushButton(Dialog)
        self.block_3_1_button.setGeometry(QtCore.QRect(1080, 104, 151, 49))
        self.block_3_1_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_1_button.setObjectName("block_3_1_button")
        self.block_3_10_button = QtWidgets.QPushButton(Dialog)
        self.block_3_10_button.setGeometry(QtCore.QRect(1080, 601, 151, 49))
        self.block_3_10_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                             "background-color: rgb(85, 170, 127);")
        self.block_3_10_button.setObjectName("block_3_10_button")
        self.block_3_3_button = QtWidgets.QPushButton(Dialog)
        self.block_3_3_button.setGeometry(QtCore.QRect(1080, 214, 151, 50))
        self.block_3_3_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_3_button.setObjectName("block_3_3_button")
        self.block_3_2_button = QtWidgets.QPushButton(Dialog)
        self.block_3_2_button.setGeometry(QtCore.QRect(1080, 159, 151, 49))
        self.block_3_2_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_2_button.setObjectName("block_3_2_button")
        self.block_3_8_button = QtWidgets.QPushButton(Dialog)
        self.block_3_8_button.setGeometry(QtCore.QRect(1080, 490, 151, 49))
        self.block_3_8_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_8_button.setObjectName("block_3_8_button")
        self.block_3_4_button = QtWidgets.QPushButton(Dialog)
        self.block_3_4_button.setGeometry(QtCore.QRect(1080, 270, 151, 49))
        self.block_3_4_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_3_4_button.setObjectName("block_3_4_button")
        self.arrow_label_2 = QtWidgets.QLabel(Dialog)
        self.arrow_label_2.setGeometry(QtCore.QRect(730, 170, 201, 31))
        self.arrow_label_2.setText("")
        self.arrow_label_2.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_label_2.setObjectName("arrow_label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(920, 110, 191, 101))
        self.label_5.setStyleSheet("font: 75 40pt \"Agency FB\";\n"
                                   "color: rgb(0, 85, 255);")
        self.label_5.setObjectName("label_5")
        self.N_label_2 = QtWidgets.QLabel(Dialog)
        self.N_label_2.setGeometry(QtCore.QRect(510, 80, 91, 91))
        self.N_label_2.setStyleSheet("font: 75 20pt \"Cambria\";\n"
                                     "color: rgb(85, 85, 255);")
        self.N_label_2.setObjectName("N_label_2")
        self.N_label_3 = QtWidgets.QLabel(Dialog)
        self.N_label_3.setGeometry(QtCore.QRect(1040, 80, 91, 91))
        self.N_label_3.setStyleSheet("font: 75 20pt \"Cambria\";\n"
                                     "color: rgb(85, 85, 255);")
        self.N_label_3.setObjectName("N_label_3")
        self.update_button = QtWidgets.QPushButton(Dialog)
        self.update_button.setGeometry(QtCore.QRect(910, 780, 111, 41))
        self.update_button.setObjectName("update_button")
        self.return_button = QtWidgets.QPushButton(Dialog)
        self.return_button.setGeometry(QtCore.QRect(1090, 780, 111, 41))
        self.return_button.setObjectName("return_button")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(210, 220, 151, 601))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.block_1_1_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_1_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_1_button.setObjectName("block_1_1_button")
        self.block_1_2_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_2_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_2_button.setObjectName("block_1_2_button")
        self.block_1_3_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_3_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_3_button.setObjectName("block_1_3_button")
        self.block_1_4_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_4_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_4_button.setObjectName("block_1_4_button")
        self.block_1_5_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_5_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_5_button.setObjectName("block_1_5_button")
        self.block_1_6_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_6_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_6_button.setObjectName("block_1_6_button")
        self.block_1_7_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_7_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_7_button.setObjectName("block_1_7_button")
        self.block_1_8_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_8_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_8_button.setObjectName("block_1_8_button")
        self.block_1_9_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_9_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                            "background-color: rgb(85, 170, 127);")
        self.block_1_9_button.setObjectName("block_1_9_button")
        self.block_1_10_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_10_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                             "background-color: rgb(85, 170, 127);")
        self.block_1_10_button.setObjectName("block_1_10_button")
        self.block_1_11_button = QtWidgets.QPushButton(self.splitter)
        self.block_1_11_button.setStyleSheet("font: 14pt \"华文琥珀\";\n"
                                             "background-color: rgb(85, 170, 127);")
        self.block_1_11_button.setObjectName("block_1_11_button")

        self.retranslateUi(Dialog)
        self.return_button.clicked.connect(Dialog.close)
        self.update_button.clicked.connect(self.update_free_block)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def update_free_block(self):
        _translate = QtCore.QCoreApplication.translate
        group_link_1 = my_disk.group_link
        index_list_1 = group_link_1.index_list
        size = group_link_1.size
        print(group_link_1.index_list)
        self.block_1_1_button.setText(_translate("Dialog", str(size)))
        try:
            index = index_list_1[-1]
        except Exception as e:
            index = 'None'
        self.block_1_2_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_1[-2]
        except Exception as e:
            index = 'None'
        self.block_1_3_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_1[-3]
        except Exception as e:
            index = 'None'
        self.block_1_4_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_1[-4]
        except Exception as e:
            index = 'None'
        self.block_1_5_button.setText(_translate("Dialog", str(index)))
        self.block_1_6_button.setText(_translate("Dialog", "......"))
        try:
            index = index_list_1[-96]
        except Exception as e:
            index = 'None'
        self.block_1_7_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_1[-97]
        except Exception as e:
            index = 'None'
        self.block_1_8_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_1[-98]
        except Exception as e:
            index = 'None'
        self.block_1_9_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_1[-99]
        except Exception as e:
            index = 'None'
        self.block_1_10_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_1[-100]
        except Exception as e:
            index = 'None'
        self.block_1_11_button.setText(_translate("Dialog", str(index)))

        group_link_2 = group_link_1.next_group
        index_list_2 = group_link_2.index_list
        size = group_link_2.size

        self.block_2_1_button.setText(_translate("Dialog", str(size)))
        try:
            index = index_list_2[-1]
        except Exception as e:
            index = 'None'
        self.block_2_2_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_2[-2]
        except Exception as e:
            index = 'None'
        self.block_2_3_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_2[-3]
        except Exception as e:
            index = 'None'
        self.block_2_4_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_2[-4]
        except Exception as e:
            index = 'None'
        self.block_2_5_button.setText(_translate("Dialog", str(index)))
        self.block_2_6_button.setText(_translate("Dialog", "......"))
        try:
            index = index_list_2[-96]
        except Exception as e:
            index = 'None'
        self.block_2_7_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_2[-97]
        except Exception as e:
            index = 'None'
        self.block_2_8_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_2[-98]
        except Exception as e:
            index = 'None'
        self.block_2_9_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_2[-99]
        except Exception as e:
            index = 'None'
        self.block_2_10_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_2[-100]
        except Exception as e:
            index = 'None'
        self.block_2_11_button.setText(_translate("Dialog", str(index)))

        group_link_3 = group_link_2.next_group
        while group_link_3.next_group is not None:
            group_link_3 = group_link_3.next_group
        index_list_3 = group_link_3.index_list
        size = group_link_3.size

        self.block_3_1_button.setText(_translate("Dialog", str(size)))
        try:
            index = index_list_3[-1]
        except Exception as e:
            index = 'None'
        self.block_3_2_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_3[-2]
        except Exception as e:
            index = 'None'
        self.block_3_3_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_3[-3]
        except Exception as e:
            index = 'None'
        self.block_3_4_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_3[-4]
        except Exception as e:
            index = 'None'
        self.block_3_5_button.setText(_translate("Dialog", str(index)))
        self.block_3_6_button.setText(_translate("Dialog", "......"))
        try:
            index = index_list_3[-20]
        except Exception as e:
            index = 'None'
        self.block_3_7_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_3[-21]
        except Exception as e:
            index = 'None'
        self.block_3_8_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_3[-22]
        except Exception as e:
            index = 'None'
        self.block_3_9_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_3[-23]
        except Exception as e:
            index = 'None'
        self.block_3_10_button.setText(_translate("Dialog", str(index)))
        try:
            index = index_list_3[-24]
        except Exception as e:
            index = 'None'
        self.block_3_11_button.setText(_translate("Dialog", str(index)))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.N_label_1.setText(_translate("Dialog", "N"))
        self.S_free_label_1.setText(_translate("Dialog", "S.free[0]"))
        self.S_free_label_2.setText(_translate("Dialog", "S.free[1]"))
        self.S_free_label_3.setText(_translate("Dialog", "S.free[99]"))
        self.block_title_label.setText(_translate("Dialog", "空闲盘块号栈"))
        self.title_label.setText(_translate("Dialog", "成组链接法展示"))
        self.block_2_5_button.setText(_translate("Dialog", "197"))
        self.block_2_6_button.setText(_translate("Dialog", "......"))
        self.block_2_9_button.setText(_translate("Dialog", "102"))
        self.block_2_11_button.setText(_translate("Dialog", "100"))
        self.block_2_7_button.setText(_translate("Dialog", "104"))
        self.block_2_1_button.setText(_translate("Dialog", "100"))
        self.block_2_10_button.setText(_translate("Dialog", "101"))
        self.block_2_3_button.setText(_translate("Dialog", "199"))
        self.block_2_2_button.setText(_translate("Dialog", "200"))
        self.block_2_8_button.setText(_translate("Dialog", "103"))
        self.block_2_4_button.setText(_translate("Dialog", "198"))
        self.block_3_5_button.setText(_translate("Dialog", "1021"))
        self.block_3_6_button.setText(_translate("Dialog", "......"))
        self.block_3_9_button.setText(_translate("Dialog", "1002"))
        self.block_3_11_button.setText(_translate("Dialog", "1000"))
        self.block_3_7_button.setText(_translate("Dialog", "1004"))
        self.block_3_1_button.setText(_translate("Dialog", "99"))
        self.block_3_10_button.setText(_translate("Dialog", "1001"))
        self.block_3_3_button.setText(_translate("Dialog", "1023"))
        self.block_3_2_button.setText(_translate("Dialog", "0"))
        self.block_3_8_button.setText(_translate("Dialog", "1003"))
        self.block_3_4_button.setText(_translate("Dialog", "1022"))
        self.label_5.setText(_translate("Dialog", "......."))
        self.N_label_2.setText(_translate("Dialog", "N"))
        self.N_label_3.setText(_translate("Dialog", "N"))
        self.update_button.setText(_translate("Dialog", "更新空闲盘块"))
        self.return_button.setText(_translate("Dialog", "返回"))
        self.block_1_1_button.setText(_translate("Dialog", "100"))
        self.block_1_2_button.setText(_translate("Dialog", "99"))
        self.block_1_3_button.setText(_translate("Dialog", "98"))
        self.block_1_4_button.setText(_translate("Dialog", "97"))
        self.block_1_5_button.setText(_translate("Dialog", "96"))
        self.block_1_6_button.setText(_translate("Dialog", "......"))
        self.block_1_7_button.setText(_translate("Dialog", "4"))
        self.block_1_8_button.setText(_translate("Dialog", "3"))
        self.block_1_9_button.setText(_translate("Dialog", "2"))
        self.block_1_10_button.setText(_translate("Dialog", "1"))
        self.block_1_11_button.setText(_translate("Dialog", "0"))


# 控制界面类
class Control_Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(1051, 760)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 501, 51))
        self.label.setStyleSheet("font: 20pt \"新宋体\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(540, 30, 481, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 180, 481, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(540, 250, 288, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(100)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 501, 51))
        self.label_2.setStyleSheet("font: 20pt \"新宋体\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(540, 330, 481, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(540, 400, 288, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(100)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 320, 501, 51))
        self.label_3.setStyleSheet("font: 20pt \"新宋体\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(540, 480, 481, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(540, 550, 288, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(100)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 470, 501, 51))
        self.label_4.setStyleSheet("font: 20pt \"新宋体\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(540, 630, 481, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(540, 700, 288, 30))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(100)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 620, 501, 51))
        self.label_5.setStyleSheet("font: 20pt \"新宋体\";")
        self.label_5.setObjectName("label_5")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(540, 100, 288, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 710, 481, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(100)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.confirm_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout_6.addWidget(self.confirm_button)
        self.delete_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_6.addWidget(self.delete_button)
        self.return_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.return_button.setObjectName("return_button")
        self.horizontalLayout_6.addWidget(self.return_button)

        self.retranslateUi(Dialog)
        self.confirm_button.clicked.connect(self.get_text)
        self.delete_button.clicked.connect(self.delete_file)
        self.pushButton_2.clicked.connect(self.lineEdit.clear)
        self.pushButton_4.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_3.clear)
        self.pushButton_8.clicked.connect(self.lineEdit_4.clear)
        self.pushButton_10.clicked.connect(self.lineEdit_5.clear)
        self.return_button.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def get_text(self):
        file_text = self.lineEdit.text()
        file_name = self.lineEdit_2.text()
        file_expansion_name = self.lineEdit_3.text()
        file_user = self.lineEdit_4.text()
        file_structure = self.lineEdit_5.text()
        file_creation_time = time.strftime('%Y-%m-%d', time.localtime(time.time()))
        dir_len = len(my_dir.directory)
        my_dir.create_file(file_name, file_expansion_name, file_creation_time, file_user, file_structure,
                           file_text, my_disk)
        dir_len_2 = len(my_dir.directory)
        if dir_len_2 > dir_len:
            QMessageBox.information(self.dialog, "Information", "文件已成功保存至目录", QMessageBox.Yes)
        else:
            QMessageBox.warning(self.dialog, 'Warning', '文件重名，请重新输入')
        try:
            my_memory.read_file_from_disk_to_memory(my_disk, file_name + '.' + file_expansion_name)
            my_memory.save_file_to_memory(8, 160, my_disk)
        except Exception as e:
            QMessageBox.critical(self.dialog, "Critical", "内存不足，存入内存失败！")

    def delete_file(self):
        dir_len = len(my_dir.directory)
        file_name = self.lineEdit_2.text()
        file_expansion_name = self.lineEdit_3.text()
        file_full_name = file_name + '.' + file_expansion_name
        my_dir.del_file_directory(file_full_name, my_disk)
        dir_len_2 = len(my_dir.directory)
        if dir_len_2 < dir_len:
            QMessageBox.information(self.dialog, "Information", "文件已成功从目录删除！")
        else:
            QMessageBox.warning(self.dialog, 'Warning', '未找到该文件，请重新输入')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请输入需要读取的文本文件路径"))
        self.pushButton_4.setText(_translate("Dialog", "清空"))
        self.label_2.setText(_translate("Dialog", "请输入文件名称"))
        self.pushButton_6.setText(_translate("Dialog", "清空"))
        self.label_3.setText(_translate("Dialog", "请输入文件后缀"))
        self.pushButton_8.setText(_translate("Dialog", "清空"))
        self.label_4.setText(_translate("Dialog", "请输入文件所有者"))
        self.pushButton_10.setText(_translate("Dialog", "清空"))
        self.label_5.setText(_translate("Dialog", "请输入文件的结构"))
        self.pushButton_2.setText(_translate("Dialog", "清空"))
        self.confirm_button.setText(_translate("Dialog", "保存文件"))
        self.delete_button.setText(_translate("Dialog", "删除文件"))
        self.return_button.setText(_translate("Dialog", "返回"))


# 内存块界面类
class Memory_Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(1101, 831)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 50, 291, 81))
        self.label.setStyleSheet("font: 20pt \"华文琥珀\";\n"
                                 "background-color: rgb(0, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 150, 111, 61))
        self.label_2.setStyleSheet("font: 16pt \"华文琥珀\";\n"
                                   "color: rgb(170, 85, 255);")
        self.label_2.setObjectName("label_2")
        self.arrow_0 = QtWidgets.QLabel(Dialog)
        self.arrow_0.setGeometry(QtCore.QRect(310, 229, 171, 41))
        self.arrow_0.setText("")
        self.arrow_0.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_0.setObjectName("arrow_0")
        self.arrow_1 = QtWidgets.QLabel(Dialog)
        self.arrow_1.setGeometry(QtCore.QRect(310, 300, 171, 31))
        self.arrow_1.setText("")
        self.arrow_1.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_1.setObjectName("arrow_1")
        self.arrow_3 = QtWidgets.QLabel(Dialog)
        self.arrow_3.setGeometry(QtCore.QRect(310, 438, 151, 41))
        self.arrow_3.setText("")
        self.arrow_3.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_3.setObjectName("arrow_3")
        self.arrow_4 = QtWidgets.QLabel(Dialog)
        self.arrow_4.setGeometry(QtCore.QRect(310, 508, 161, 41))
        self.arrow_4.setText("")
        self.arrow_4.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_4.setObjectName("arrow_4")
        self.arrow_6 = QtWidgets.QLabel(Dialog)
        self.arrow_6.setGeometry(QtCore.QRect(310, 649, 151, 31))
        self.arrow_6.setText("")
        self.arrow_6.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_6.setObjectName("arrow_6")
        self.arrow_7 = QtWidgets.QLabel(Dialog)
        self.arrow_7.setGeometry(QtCore.QRect(310, 720, 151, 41))
        self.arrow_7.setText("")
        self.arrow_7.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_7.setObjectName("arrow_7")
        self.arrow_5 = QtWidgets.QLabel(Dialog)
        self.arrow_5.setGeometry(QtCore.QRect(310, 578, 151, 41))
        self.arrow_5.setText("")
        self.arrow_5.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_5.setObjectName("arrow_5")
        self.arrow_2 = QtWidgets.QLabel(Dialog)
        self.arrow_2.setGeometry(QtCore.QRect(310, 371, 171, 31))
        self.arrow_2.setText("")
        self.arrow_2.setPixmap(QtGui.QPixmap("gui_pic/图片1.png"))
        self.arrow_2.setObjectName("arrow_2")
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(470, 220, 261, 541))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.page_0 = QtWidgets.QPushButton(self.splitter_2)
        self.page_0.setStyleSheet("font: 14pt \"黑体\";")
        self.page_0.setObjectName("page_0")
        self.page_1 = QtWidgets.QPushButton(self.splitter_2)
        self.page_1.setStyleSheet("font: 14pt \"黑体\";")
        self.page_1.setObjectName("page_1")
        self.page_2 = QtWidgets.QPushButton(self.splitter_2)
        self.page_2.setStyleSheet("font: 14pt \"黑体\";")
        self.page_2.setObjectName("page_2")
        self.page_3 = QtWidgets.QPushButton(self.splitter_2)
        self.page_3.setStyleSheet("font: 14pt \"黑体\";")
        self.page_3.setObjectName("page_3")
        self.page_4 = QtWidgets.QPushButton(self.splitter_2)
        self.page_4.setStyleSheet("font: 14pt \"黑体\";")
        self.page_4.setObjectName("page_4")
        self.page_5 = QtWidgets.QPushButton(self.splitter_2)
        self.page_5.setStyleSheet("font: 14pt \"黑体\";")
        self.page_5.setObjectName("page_5")
        self.page_6 = QtWidgets.QPushButton(self.splitter_2)
        self.page_6.setStyleSheet("font: 14pt \"黑体\";")
        self.page_6.setObjectName("page_6")
        self.page_7 = QtWidgets.QPushButton(self.splitter_2)
        self.page_7.setStyleSheet("font: 14pt \"黑体\";")
        self.page_7.setObjectName("page_7")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(560, 150, 111, 61))
        self.label_11.setStyleSheet("font: 16pt \"华文琥珀\";\n"
                                    "color: rgb(170, 85, 255);")
        self.label_11.setObjectName("label_11")
        self.splitter_3 = QtWidgets.QSplitter(Dialog)
        self.splitter_3.setGeometry(QtCore.QRect(780, 220, 261, 541))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.data_0 = QtWidgets.QPushButton(self.splitter_3)
        self.data_0.setStyleSheet("font: 14pt \"黑体\";")
        self.data_0.setObjectName("data_0")
        self.data_1 = QtWidgets.QPushButton(self.splitter_3)
        self.data_1.setStyleSheet("font: 14pt \"黑体\";")
        self.data_1.setObjectName("data_1")
        self.data_2 = QtWidgets.QPushButton(self.splitter_3)
        self.data_2.setStyleSheet("font: 14pt \"黑体\";")
        self.data_2.setObjectName("data_2")
        self.data_3 = QtWidgets.QPushButton(self.splitter_3)
        self.data_3.setStyleSheet("font: 14pt \"黑体\";")
        self.data_3.setObjectName("data_3")
        self.data_4 = QtWidgets.QPushButton(self.splitter_3)
        self.data_4.setStyleSheet("font: 14pt \"黑体\";")
        self.data_4.setObjectName("data_4")
        self.data_5 = QtWidgets.QPushButton(self.splitter_3)
        self.data_5.setStyleSheet("font: 14pt \"黑体\";")
        self.data_5.setObjectName("data_5")
        self.data_6 = QtWidgets.QPushButton(self.splitter_3)
        self.data_6.setStyleSheet("font: 14pt \"黑体\";")
        self.data_6.setObjectName("data_6")
        self.data_7 = QtWidgets.QPushButton(self.splitter_3)
        self.data_7.setStyleSheet("font: 14pt \"黑体\";")
        self.data_7.setObjectName("data_7")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(870, 150, 111, 61))
        self.label_12.setStyleSheet("font: 16pt \"华文琥珀\";\n"
                                    "color: rgb(170, 85, 255);")
        self.label_12.setObjectName("label_12")
        self.clear_button = QtWidgets.QPushButton(Dialog)
        self.clear_button.setGeometry(QtCore.QRect(310, 780, 93, 28))
        self.clear_button.setObjectName("clear_button")
        self.reset_button = QtWidgets.QPushButton(Dialog)
        self.reset_button.setGeometry(QtCore.QRect(500, 780, 93, 28))
        self.reset_button.setObjectName("reset_button")
        self.next_button = QtWidgets.QPushButton(Dialog)
        self.next_button.setGeometry(QtCore.QRect(690, 780, 93, 28))
        self.next_button.setObjectName("next_button")
        self.return_button = QtWidgets.QPushButton(Dialog)
        self.return_button.setGeometry(QtCore.QRect(880, 780, 93, 28))
        self.return_button.setObjectName("return_button")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(20, 220, 261, 541))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.memory_0 = QtWidgets.QPushButton(self.splitter)
        self.memory_0.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_0.setObjectName("memory_0")
        self.memory_1 = QtWidgets.QPushButton(self.splitter)
        self.memory_1.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_1.setObjectName("memory_1")
        self.memory_2 = QtWidgets.QPushButton(self.splitter)
        self.memory_2.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_2.setObjectName("memory_2")
        self.memory_3 = QtWidgets.QPushButton(self.splitter)
        self.memory_3.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_3.setObjectName("memory_3")
        self.memory_4 = QtWidgets.QPushButton(self.splitter)
        self.memory_4.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_4.setObjectName("memory_4")
        self.memory_5 = QtWidgets.QPushButton(self.splitter)
        self.memory_5.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_5.setObjectName("memory_5")
        self.memory_6 = QtWidgets.QPushButton(self.splitter)
        self.memory_6.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_6.setObjectName("memory_6")
        self.memory_7 = QtWidgets.QPushButton(self.splitter)
        self.memory_7.setStyleSheet("font: 14pt \"黑体\";")
        self.memory_7.setObjectName("memory_7")

        self.retranslateUi(Dialog)
        self.clear_button.clicked.connect(self.clear_memory)
        self.reset_button.clicked.connect(self.reset_blocks)
        self.next_button.clicked.connect(self.get_next_blocks)
        self.return_button.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def clear_memory(self):
        my_memory.recover_memory()
        QMessageBox.information(self.dialog, "Information", "内存已成功清空！")

    def reset_blocks(self):
        global memory_index
        memory_index = 0
        _translate = QtCore.QCoreApplication.translate
        self.page_0.setText(_translate("Dialog", "None"))
        self.page_1.setText(_translate("Dialog", "None"))
        self.page_2.setText(_translate("Dialog", "None"))
        self.page_3.setText(_translate("Dialog", "None"))
        self.page_4.setText(_translate("Dialog", "None"))
        self.page_5.setText(_translate("Dialog", "None"))
        self.page_6.setText(_translate("Dialog", "None"))
        self.page_7.setText(_translate("Dialog", "None"))
        self.data_0.setText(_translate("Dialog", "None"))
        self.data_1.setText(_translate("Dialog", "None"))
        self.data_2.setText(_translate("Dialog", "None"))
        self.data_3.setText(_translate("Dialog", "None"))
        self.data_4.setText(_translate("Dialog", "None"))
        self.data_5.setText(_translate("Dialog", "None"))
        self.data_6.setText(_translate("Dialog", "None"))
        self.data_7.setText(_translate("Dialog", "None"))
        self.memory_0.setText(_translate("Dialog", "0"))
        self.memory_1.setText(_translate("Dialog", "1"))
        self.memory_2.setText(_translate("Dialog", "2"))
        self.memory_3.setText(_translate("Dialog", "3"))
        self.memory_4.setText(_translate("Dialog", "4"))
        self.memory_5.setText(_translate("Dialog", "5"))
        self.memory_6.setText(_translate("Dialog", "6"))
        self.memory_7.setText(_translate("Dialog", "7"))


    # 返回每一块的信息并输出
    def get_next_blocks(self):
        global memory_index
        if memory_index >= 8:
            QMessageBox.warning(self.dialog, "Warning", "已经到内存的最后！")
            return
        memory_list = my_memory.memory_list[memory_index*8:(memory_index + 1)*8]
        _translate = QtCore.QCoreApplication.translate
        self.memory_0.setText(_translate("Dialog", str(memory_list[0].index)))
        self.memory_1.setText(_translate("Dialog", str(memory_list[1].index)))
        self.memory_2.setText(_translate("Dialog", str(memory_list[2].index)))
        self.memory_3.setText(_translate("Dialog", str(memory_list[3].index)))
        self.memory_4.setText(_translate("Dialog", str(memory_list[4].index)))
        self.memory_5.setText(_translate("Dialog", str(memory_list[5].index)))
        self.memory_6.setText(_translate("Dialog", str(memory_list[6].index)))
        self.memory_7.setText(_translate("Dialog", str(memory_list[7].index)))

        page_index = str(memory_list[0].data.index) if memory_list[0].data is not None else 'None'
        self.page_0.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[1].data.index) if memory_list[1].data is not None else 'None'
        self.page_1.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[2].data.index) if memory_list[2].data is not None else 'None'
        self.page_2.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[3].data.index) if memory_list[3].data is not None else 'None'
        self.page_3.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[4].data.index) if memory_list[4].data is not None else 'None'
        self.page_4.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[5].data.index) if memory_list[5].data is not None else 'None'
        self.page_5.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[6].data.index) if memory_list[6].data is not None else 'None'
        self.page_6.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[7].data.index) if memory_list[7].data is not None else 'None'
        self.page_7.setText(_translate("Dialog", page_index))

        page_index = str(memory_list[0].data.data) if memory_list[0].data is not None else 'None'
        self.data_0.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[1].data.data) if memory_list[1].data is not None else 'None'
        self.data_1.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[2].data.data) if memory_list[2].data is not None else 'None'
        self.data_2.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[3].data.data) if memory_list[3].data is not None else 'None'
        self.data_3.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[4].data.data) if memory_list[4].data is not None else 'None'
        self.data_4.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[5].data.data) if memory_list[5].data is not None else 'None'
        self.data_5.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[6].data.data) if memory_list[6].data is not None else 'None'
        self.data_6.setText(_translate("Dialog", page_index))
        page_index = str(memory_list[7].data.data) if memory_list[7].data is not None else 'None'
        self.data_7.setText(_translate("Dialog", page_index))

        memory_index += 1

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "   内存块显示界面"))
        self.label_2.setText(_translate("Dialog", "内存块"))
        self.page_0.setText(_translate("Dialog", "None"))
        self.page_1.setText(_translate("Dialog", "None"))
        self.page_2.setText(_translate("Dialog", "None"))
        self.page_3.setText(_translate("Dialog", "None"))
        self.page_4.setText(_translate("Dialog", "None"))
        self.page_5.setText(_translate("Dialog", "None"))
        self.page_6.setText(_translate("Dialog", "None"))
        self.page_7.setText(_translate("Dialog", "None"))
        self.label_11.setText(_translate("Dialog", "页"))
        self.data_0.setText(_translate("Dialog", "None"))
        self.data_1.setText(_translate("Dialog", "None"))
        self.data_2.setText(_translate("Dialog", "None"))
        self.data_3.setText(_translate("Dialog", "None"))
        self.data_4.setText(_translate("Dialog", "None"))
        self.data_5.setText(_translate("Dialog", "None"))
        self.data_6.setText(_translate("Dialog", "None"))
        self.data_7.setText(_translate("Dialog", "None"))
        self.label_12.setText(_translate("Dialog", "内容"))
        self.next_button.setText(_translate("Dialog", "下一部分"))
        self.clear_button.setText(_translate("Dialog", "清空内存"))
        self.reset_button.setText(_translate("Dialog", "刷新内存"))
        self.return_button.setText(_translate("Dialog", "返回"))
        self.memory_0.setText(_translate("Dialog", "0"))
        self.memory_1.setText(_translate("Dialog", "1"))
        self.memory_2.setText(_translate("Dialog", "2"))
        self.memory_3.setText(_translate("Dialog", "3"))
        self.memory_4.setText(_translate("Dialog", "4"))
        self.memory_5.setText(_translate("Dialog", "5"))
        self.memory_6.setText(_translate("Dialog", "6"))
        self.memory_7.setText(_translate("Dialog", "7"))


# 目录管理类界面
class Dir_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(981, 638)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(140, 110, 691, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        for i in range(0, 5):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 4, item)
        self.return_button = QtWidgets.QPushButton(Dialog)
        self.return_button.setGeometry(QtCore.QRect(800, 560, 93, 28))
        self.return_button.setObjectName("return_button")
        self.update_button = QtWidgets.QPushButton(Dialog)
        self.update_button.setGeometry(QtCore.QRect(610, 560, 93, 28))
        self.update_button.setObjectName("update_button")

        self.retranslateUi(Dialog)
        self.update_button.clicked.connect(self.dir_fun)
        self.return_button.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def dir_fun(self):
        _translate = QtCore.QCoreApplication.translate
        for i in range(0, 5):
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 2)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 4)
            item.setText(_translate("Dialog", "None"))
        for dir_index in range(0, len(my_dir.directory)):
            mess_1 = my_dir.directory[dir_index].file_full_name
            mess_2 = my_dir.directory[dir_index].user
            mess_3 = my_dir.directory[dir_index].creation_time
            mess_4 = my_dir.directory[dir_index].structure
            mess_5 = my_dir.directory[dir_index].address
            mess_5 = str(mess_5[0]) + '-' + str(mess_5[-1])
            item = self.tableWidget.verticalHeaderItem(dir_index)
            item = self.tableWidget.item(dir_index, 0)
            item.setText(_translate("Dialog", mess_1))
            item = self.tableWidget.item(dir_index, 1)
            item.setText(_translate("Dialog", mess_2))
            item = self.tableWidget.item(dir_index, 2)
            item.setText(_translate("Dialog", mess_3))
            item = self.tableWidget.item(dir_index, 3)
            item.setText(_translate("Dialog", mess_4))
            item = self.tableWidget.item(dir_index, 4)
            item.setText(_translate("Dialog", mess_5))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "目录1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "目录2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "目录3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "目录4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "目录5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "所有者"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "创建时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "文件结构"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "存放地址"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        for i in range(0, 5):
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 2)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("Dialog", "None"))
            item = self.tableWidget.item(i, 4)
            item.setText(_translate("Dialog", "None"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.return_button.setText(_translate("Dialog", "返回"))
        self.update_button.setText(_translate("Dialog", "更新"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    main_ui = Ui_MainWindow()
    main_ui.setupUi(MainWindow)

    # 目录管理窗口
    Dir_Dialog = QtWidgets.QDialog()
    dir_ui = Dir_Ui_Dialog()
    dir_ui.setupUi(Dir_Dialog)

    # 控制界面窗口
    Control_Dialog = QtWidgets.QDialog()
    control_ui = Control_Ui_Dialog()
    control_ui.setupUi(Control_Dialog)

    # 内存块窗口
    Memory_Dialog = QtWidgets.QDialog()
    memory_ui = Memory_Ui_Dialog()
    memory_ui.setupUi(Memory_Dialog)

    # 外存块窗口
    Disk_Dialog = QtWidgets.QDialog()
    disk_ui = Disk_Ui_Dialog()
    disk_ui.setupUi(Disk_Dialog)

    # 设置窗口链接调用
    main_ui.control_button.clicked.connect(Control_Dialog.show)
    main_ui.dir_button.clicked.connect(Dir_Dialog.show)
    main_ui.memory_button.clicked.connect(Memory_Dialog.show)
    main_ui.disk_button.clicked.connect(Disk_Dialog.show)

    MainWindow.show()
    sys.exit(app.exec_())
